// Code generated by github.com/otherview/solgen. DO NOT EDIT.
// SPDX-License-Identifier: MIT
// Contract: ComplexContract (solc 0.8.20)

package complexcontract

import (
	"encoding/hex"
	"errors"
	"fmt"
	"math/big"
	"reflect"
	"strings"
)

// Contract metadata
var _abiJSON = "[\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"function\",\n\t\t\t\t\t\"name\": \"complexFunction\",\n\t\t\t\t\t\"inputs\": [\n\t\t\t\t\t\t{\"name\": \"addresses\", \"type\": \"address[]\"},\n\t\t\t\t\t\t{\"name\": \"amounts\", \"type\": \"uint256[]\"},\n\t\t\t\t\t\t{\"name\": \"data\", \"type\": \"bytes\"},\n\t\t\t\t\t\t{\"name\": \"flag\", \"type\": \"bool\"}\n\t\t\t\t\t],\n\t\t\t\t\t\"outputs\": [\n\t\t\t\t\t\t{\"name\": \"success\", \"type\": \"bool\"},\n\t\t\t\t\t\t{\"name\": \"results\", \"type\": \"uint256[]\"}\n\t\t\t\t\t],\n\t\t\t\t\t\"stateMutability\": \"nonpayable\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"function\",\n\t\t\t\t\t\"name\": \"getMapping\",\n\t\t\t\t\t\"inputs\": [{\"name\": \"key\", \"type\": \"bytes32\"}],\n\t\t\t\t\t\"outputs\": [{\"name\": \"value\", \"type\": \"string\"}],\n\t\t\t\t\t\"stateMutability\": \"view\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"event\",\n\t\t\t\t\t\"name\": \"ComplexEvent\", \n\t\t\t\t\t\"inputs\": [\n\t\t\t\t\t\t{\"name\": \"user\", \"type\": \"address\", \"indexed\": true},\n\t\t\t\t\t\t{\"name\": \"data\", \"type\": \"bytes\", \"indexed\": false},\n\t\t\t\t\t\t{\"name\": \"timestamp\", \"type\": \"uint256\", \"indexed\": true}\n\t\t\t\t\t]\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"error\",\n\t\t\t\t\t\"name\": \"ComplexError\",\n\t\t\t\t\t\"inputs\": [\n\t\t\t\t\t\t{\"name\": \"reason\", \"type\": \"string\"},\n\t\t\t\t\t\t{\"name\": \"code\", \"type\": \"uint256\"}\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t]"

// ABI returns the contract ABI as a JSON string
func ABI() string {
	return _abiJSON
}

// Bytecode contains the contract creation bytecode
var Bytecode = HexData("0x608060405234801561001057600080fd5b50610abc806100206000396000f3fe")

// DeployedBytecode contains the contract runtime bytecode
var DeployedBytecode = HexData("0x6080604052348015600f57600080fd5b50600436106100365760003560e01c8063abcd123414603a5780634567890114603f565b5b600080fd5b005b005b600080fd5b6000819050919050565b60558160048565b8114605f57600080fd5b50565b6000813590506070816050565b92915050565b6000602082840312156088576087600b565b5b600060948482850160635b915050929150505056fea264697066735822")

// Address represents a 20-byte Ethereum address
type Address [20]byte

// String returns the hex string representation of the address
func (a Address) String() string {
	return "0x" + hex.EncodeToString(a[:])
}

// Hash represents a 32-byte hash
type Hash [32]byte

// String returns the hex string representation of the hash
func (h Hash) String() string {
	return "0x" + hex.EncodeToString(h[:])
}

// Bytes returns the hash as a byte slice
func (h Hash) Bytes() []byte {
	return h[:]
}

// AddressFromHex creates an Address from a hex string
func AddressFromHex(s string) Address {
	var addr Address
	if strings.HasPrefix(s, "0x") {
		s = s[2:]
	}
	if len(s) != 40 {
		panic("invalid address hex string length")
	}
	decoded, err := hex.DecodeString(s)
	if err != nil {
		panic("invalid address hex string: " + err.Error())
	}
	copy(addr[:], decoded)
	return addr
}

// HashFromHex creates a Hash from a hex string
func HashFromHex(s string) Hash {
	var hash Hash
	if strings.HasPrefix(s, "0x") {
		s = s[2:]
	}
	if len(s) != 64 {
		panic("invalid hash hex string length")
	}
	decoded, err := hex.DecodeString(s)
	if err != nil {
		panic("invalid hash hex string: " + err.Error())
	}
	copy(hash[:], decoded)
	return hash
}

// HexData provides convenient access to hex-encoded byte data
type HexData string

// Hex returns the hex string representation
func (h HexData) Hex() string {
	return string(h)
}

// Bytes returns the decoded bytes from the hex string
func (h HexData) Bytes() []byte {
	hexStr := string(h)
	if hexStr == "" {
		return nil
	}
	if strings.HasPrefix(hexStr, "0x") {
		hexStr = hexStr[2:]
	}
	decoded, err := hex.DecodeString(hexStr)
	if err != nil {
		panic("invalid hex data: " + err.Error())
	}
	return decoded
}

// ABI Encoding Implementation

// encodeUint256 encodes a uint256 value to 32 bytes (big-endian)
func encodeUint256(val interface{}) ([]byte, error) {
	result := make([]byte, 32)
	switch v := val.(type) {
	case *big.Int:
		if v.Sign() < 0 {
			return nil, errors.New("negative values not supported for uint256")
		}
		if v.BitLen() > 256 {
			return nil, errors.New("value too large for uint256")
		}
		v.FillBytes(result)
		return result, nil
	case uint64:
		big.NewInt(0).SetUint64(v).FillBytes(result)
		return result, nil
	case int64:
		if v < 0 {
			return nil, errors.New("negative values not supported for uint256")
		}
		big.NewInt(v).FillBytes(result)
		return result, nil
	case int:
		if v < 0 {
			return nil, errors.New("negative values not supported for uint256")
		}
		big.NewInt(int64(v)).FillBytes(result)
		return result, nil
	default:
		return nil, fmt.Errorf("unsupported type for uint256: %T", v)
	}
}

// encodeInt256 encodes a signed 256-bit integer to 32 bytes using two's complement.
// Valid range: [-2^255, 2^255-1].
func encodeInt256(val interface{}) ([]byte, error) {
	result := make([]byte, 32)
	switch v := val.(type) {
	case *big.Int:
		if v.Sign() >= 0 {
			// Positive: valid range [0, 2^255-1] → BitLen must be ≤ 255.
			if v.BitLen() > 255 {
				return nil, errors.New("value too large for int256")
			}
			v.FillBytes(result)
		} else {
			// Negative: valid range [-2^255, -1].
			// abs(-2^255) has BitLen == 256, which is the boundary.
			abs := new(big.Int).Neg(v)
			minNeg := new(big.Int).Lsh(big.NewInt(1), 255) // 2^255
			if abs.Cmp(minNeg) > 0 {
				return nil, errors.New("value too small for int256")
			}
			// Two's-complement: compute 2^256 + v = 2^256 - abs(v).
			mask := new(big.Int).Lsh(big.NewInt(1), 256)
			new(big.Int).Add(mask, v).FillBytes(result)
		}
		return result, nil
	case int64:
		return encodeInt256(big.NewInt(v))
	case int:
		return encodeInt256(big.NewInt(int64(v)))
	default:
		return nil, fmt.Errorf("unsupported type for int256: %T", v)
	}
}

// encodeAddress encodes an address to 32 bytes (zero-padded)
func encodeAddress(addr Address) ([]byte, error) {
	result := make([]byte, 32)
	copy(result[12:32], addr[:])
	return result, nil
}

// encodeBool encodes a boolean to 32 bytes
func encodeBool(val bool) ([]byte, error) {
	result := make([]byte, 32)
	if val {
		result[31] = 1
	}
	return result, nil
}

// encodeBytes encodes dynamic bytes
func encodeBytes(data []byte) ([]byte, error) {
	// Length (32 bytes) + data (padded to multiple of 32 bytes)
	length := len(data)
	lengthBytes, err := encodeUint256(uint64(length))
	if err != nil {
		return nil, err
	}

	// Pad data to multiple of 32 bytes
	paddedLength := ((length + 31) / 32) * 32
	paddedData := make([]byte, paddedLength)
	copy(paddedData, data)

	return append(lengthBytes, paddedData...), nil
}

// encodeString encodes a string as dynamic bytes
func encodeString(str string) ([]byte, error) {
	return encodeBytes([]byte(str))
}

// encodeFixedBytes encodes fixed-size bytes (e.g., bytes32) as a single static
// 32-byte word: the value is left-aligned and right-padded with zeros.
func encodeFixedBytes(val []byte, size int) ([]byte, error) {
	if size < 1 || size > 32 {
		return nil, fmt.Errorf("invalid fixed bytes size: %d", size)
	}
	if len(val) != size {
		return nil, fmt.Errorf("fixed bytes length mismatch: got %d, want %d", len(val), size)
	}
	result := make([]byte, 32)
	copy(result, val)
	return result, nil
}

// encodeArg encodes a single ABI argument, returning its encoded bytes and
// whether it is a dynamic type (which gets a 32-byte offset pointer in the head
// and its data in the tail). It is the per-argument core shared by Pack.
func encodeArg(arg any) ([]byte, bool, error) {
	switch v := arg.(type) {
	case *big.Int:
		if v.Sign() < 0 {
			d, err := encodeInt256(v)
			return d, false, err
		}
		d, err := encodeUint256(v)
		return d, false, err
	case uint8:
		d, err := encodeUint256(uint64(v))
		return d, false, err
	case uint16:
		d, err := encodeUint256(uint64(v))
		return d, false, err
	case uint32:
		d, err := encodeUint256(uint64(v))
		return d, false, err
	case uint64:
		d, err := encodeUint256(v)
		return d, false, err
	case int8:
		d, err := encodeInt256(big.NewInt(int64(v)))
		return d, false, err
	case int16:
		d, err := encodeInt256(big.NewInt(int64(v)))
		return d, false, err
	case int32:
		d, err := encodeInt256(big.NewInt(int64(v)))
		return d, false, err
	case int64:
		d, err := encodeInt256(big.NewInt(v))
		return d, false, err
	case Address:
		d, err := encodeAddress(v)
		return d, false, err
	case bool:
		d, err := encodeBool(v)
		return d, false, err
	case string:
		d, err := encodeString(v)
		return d, true, err
	case []byte:
		d, err := encodeBytes(v)
		return d, true, err
	case Hash:
		d, err := encodeFixedBytes(v[:], 32)
		return d, false, err
	case [32]byte:
		d, err := encodeFixedBytes(v[:], 32)
		return d, false, err
	default:
		rt := reflect.TypeOf(arg)
		if rt != nil && rt.Kind() == reflect.Array {
			// Fixed-size byte array bytesN (1 <= N <= 32): one static word.
			if rt.Elem().Kind() == reflect.Uint8 && rt.Len() <= 32 {
				rv := reflect.ValueOf(arg)
				b := make([]byte, rv.Len())
				reflect.Copy(reflect.ValueOf(b), rv)
				d, err := encodeFixedBytes(b, len(b))
				return d, false, err
			}
			// Fixed-size array [N]T of static elements: N inline static words.
			rv := reflect.ValueOf(arg)
			var out []byte
			for i := 0; i < rv.Len(); i++ {
				elemData, elemDynamic, err := encodeArg(rv.Index(i).Interface())
				if err != nil {
					return nil, false, fmt.Errorf("encoding array element %d: %w", i, err)
				}
				if elemDynamic {
					return nil, false, fmt.Errorf("unsupported dynamic element in fixed-size array: %T", arg)
				}
				out = append(out, elemData...)
			}
			return out, false, nil
		}
		return nil, false, fmt.Errorf("unsupported argument type: %T", arg)
	}
}

// ABI Decoding Implementation

// decodeUint256 decodes a uint256 from 32 bytes to *big.Int
func decodeUint256(data []byte) (*big.Int, error) {
	if len(data) < 32 {
		return nil, errors.New("insufficient data for uint256")
	}
	return new(big.Int).SetBytes(data[:32]), nil
}

// decodeInt256 decodes a signed 256-bit integer from 32 bytes
func decodeInt256(data []byte) (*big.Int, error) {
	if len(data) < 32 {
		return nil, errors.New("insufficient data for int256")
	}

	result := new(big.Int).SetBytes(data[:32])

	// Check if negative (MSB is set)
	if data[0]&0x80 != 0 {
		// Convert from two's complement
		// Create mask with all bits set for 256-bit number
		mask := new(big.Int).Lsh(big.NewInt(1), 256)
		mask.Sub(mask, big.NewInt(1))

		// XOR with mask and add 1 to get absolute value
		result.Xor(result, mask)
		result.Add(result, big.NewInt(1))
		result.Neg(result)
	}

	return result, nil
}

// decodeAddress decodes an address from 32 bytes
func decodeAddress(data []byte) (Address, error) {
	if len(data) < 32 {
		return Address{}, errors.New("insufficient data for address")
	}
	var addr Address
	copy(addr[:], data[12:32])
	return addr, nil
}

// decodeBool decodes a boolean from 32 bytes
func decodeBool(data []byte) (bool, error) {
	if len(data) < 32 {
		return false, errors.New("insufficient data for bool")
	}
	return data[31] != 0, nil
}

// decodeBytes decodes dynamic bytes
func decodeBytes(data []byte, offset int) ([]byte, int, error) {
	if len(data) < offset+32 {
		return nil, 0, errors.New("insufficient data for bytes length")
	}
	lengthBig, err := decodeUint256(data[offset : offset+32])
	if err != nil {
		return nil, 0, fmt.Errorf("decoding bytes length: %w", err)
	}
	if !lengthBig.IsUint64() {
		return nil, 0, errors.New("bytes length too large")
	}
	length := int(lengthBig.Uint64())
	if len(data) < offset+32+length {
		return nil, 0, errors.New("insufficient data for bytes content")
	}
	result := make([]byte, length)
	copy(result, data[offset+32:offset+32+length])
	// Calculate next offset (padded to 32 bytes)
	paddedLength := ((length + 31) / 32) * 32
	return result, offset + 32 + paddedLength, nil
}

// decodeFixedBytes decodes fixed-size bytes (e.g., bytes32)
func decodeFixedBytes(data []byte, size int) ([]byte, error) {
	if len(data) < 32 {
		return nil, errors.New("insufficient data for fixed bytes")
	}
	if size > 32 {
		return nil, errors.New("fixed bytes size too large")
	}
	result := make([]byte, size)
	copy(result, data[:size])
	return result, nil
}

// decode various fixed-size byte arrays
func decodeBytes1(data []byte) ([1]byte, error) {
	bytes, err := decodeFixedBytes(data, 1)
	if err != nil {
		return [1]byte{}, err
	}
	var result [1]byte
	copy(result[:], bytes)
	return result, nil
}

func decodeBytes32(data []byte) ([32]byte, error) {
	bytes, err := decodeFixedBytes(data, 32)
	if err != nil {
		return [32]byte{}, err
	}
	var result [32]byte
	copy(result[:], bytes)
	return result, nil
}

// decodeArray decodes dynamic arrays
func decodeArray(data []byte, offset int, elemDecoder func([]byte) (interface{}, error)) ([]interface{}, int, error) {
	if len(data) < offset+32 {
		return nil, 0, errors.New("insufficient data for array length")
	}

	lengthBig, err := decodeUint256(data[offset : offset+32])
	if err != nil {
		return nil, 0, fmt.Errorf("decoding array length: %w", err)
	}
	if !lengthBig.IsUint64() {
		return nil, 0, errors.New("array length too large")
	}
	length := int(lengthBig.Uint64())

	currentOffset := offset + 32
	result := make([]interface{}, length)

	for i := 0; i < length; i++ {
		if len(data) < currentOffset+32 {
			return nil, 0, fmt.Errorf("insufficient data for array element %d", i)
		}
		elem, err := elemDecoder(data[currentOffset : currentOffset+32])
		if err != nil {
			return nil, 0, fmt.Errorf("decoding array element %d: %w", i, err)
		}
		result[i] = elem
		currentOffset += 32
	}

	return result, currentOffset, nil
}

// Array element decoders (internal use)
func decodeUint256ArrayElement(data []byte) (interface{}, error) {
	return decodeUint256(data)
}

func decodeInt256ArrayElement(data []byte) (interface{}, error) {
	return decodeInt256(data)
}

func decodeAddressArrayElement(data []byte) (interface{}, error) {
	return decodeAddress(data)
}

func decodeBoolArrayElement(data []byte) (interface{}, error) {
	return decodeBool(data)
}

// readOffset reads a 32-byte ABI offset/length word at head position pos and
// returns it as an int.
func readOffset(data []byte, pos int) (int, error) {
	if len(data) < pos+32 {
		return 0, errors.New("insufficient data for offset pointer")
	}
	p, err := decodeUint256(data[pos : pos+32])
	if err != nil {
		return 0, fmt.Errorf("decoding offset pointer: %w", err)
	}
	if !p.IsUint64() {
		return 0, errors.New("offset pointer too large")
	}
	return int(p.Uint64()), nil
}

// decodeStaticSliceAt decodes a dynamic array of static (32-byte) elements. pos
// is the head position holding the offset pointer to the array data; dec decodes
// a single element from its 32-byte word.
func decodeStaticSliceAt[T any](data []byte, pos int, dec func([]byte) (T, error)) ([]T, error) {
	arrPos, err := readOffset(data, pos)
	if err != nil {
		return nil, err
	}
	length, err := readOffset(data, arrPos)
	if err != nil {
		return nil, fmt.Errorf("decoding array length: %w", err)
	}
	out := make([]T, length)
	cur := arrPos + 32
	for i := 0; i < length; i++ {
		if len(data) < cur+32 {
			return nil, fmt.Errorf("insufficient data for array element %d", i)
		}
		v, err := dec(data[cur : cur+32])
		if err != nil {
			return nil, fmt.Errorf("decoding array element %d: %w", i, err)
		}
		out[i] = v
		cur += 32
	}
	return out, nil
}

// decodeStaticFixedArray decodes size consecutive static (32-byte) elements
// starting at pos into a slice; the caller copies it into the fixed-size [N]T
// value. dec decodes a single element from its 32-byte word.
func decodeStaticFixedArray[T any](data []byte, pos, size int, dec func([]byte) (T, error)) ([]T, error) {
	out := make([]T, size)
	for i := 0; i < size; i++ {
		if len(data) < pos+(i+1)*32 {
			return nil, fmt.Errorf("insufficient data for fixed array element %d", i)
		}
		v, err := dec(data[pos+i*32 : pos+(i+1)*32])
		if err != nil {
			return nil, fmt.Errorf("decoding fixed array element %d: %w", i, err)
		}
		out[i] = v
	}
	return out, nil
}

// decodeUint8 decodes a uint8 from 32 bytes
func decodeUint8(data []byte) (uint8, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint8")
	}
	// Verify upper bytes are zero
	for i := 0; i < 31; i++ {
		if data[i] != 0 {
			return 0, errors.New("invalid uint8 encoding")
		}
	}
	return data[31], nil
}

// decodeUint16 decodes a uint16 from 32 bytes
func decodeUint16(data []byte) (uint16, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint16")
	}
	// Verify upper bytes are zero
	for i := 0; i < 30; i++ {
		if data[i] != 0 {
			return 0, errors.New("invalid uint16 encoding")
		}
	}
	return uint16(data[30])<<8 | uint16(data[31]), nil
}

// decodeUint32 decodes a uint32 from 32 bytes
func decodeUint32(data []byte) (uint32, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint32")
	}
	// Verify upper bytes are zero
	for i := 0; i < 28; i++ {
		if data[i] != 0 {
			return 0, errors.New("invalid uint32 encoding")
		}
	}
	var result uint32
	for i := 28; i < 32; i++ {
		result = (result << 8) | uint32(data[i])
	}
	return result, nil
}

// decodeUint64 decodes a uint64 from 32 bytes
func decodeUint64(data []byte) (uint64, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint64")
	}
	// Check if value exceeds uint64 range
	for i := 0; i < 24; i++ {
		if data[i] != 0 {
			return 0, errors.New("value exceeds uint64 range")
		}
	}
	var result uint64
	for i := 24; i < 32; i++ {
		result = (result << 8) | uint64(data[i])
	}
	return result, nil
}

// decodeInt64 decodes an int64 from 32 bytes (ABI sign-extended big-endian).
func decodeInt64(data []byte) (int64, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for int64")
	}

	// ABI sign-extension: bytes 0-23 must all match the sign byte
	// (0x00 for non-negative, 0xFF for negative).
	isNegative := data[0]&0x80 != 0
	expectedByte := byte(0)
	if isNegative {
		expectedByte = 0xFF
	}
	for i := 0; i < 24; i++ {
		if data[i] != expectedByte {
			return 0, errors.New("value exceeds int64 range")
		}
	}

	// Assemble the int64 from the last 8 bytes.
	// Because data[24..31] already hold the correct two's-complement
	// representation, no further sign extension is needed.
	var result int64
	for i := 24; i < 32; i++ {
		result = (result << 8) | int64(data[i])
	}
	return result, nil
}

// decodeHash decodes a 32-byte hash
func decodeHash(data []byte) (Hash, error) {
	if len(data) < 32 {
		return Hash{}, errors.New("insufficient data for hash")
	}
	var hash Hash
	copy(hash[:], data[:32])
	return hash, nil
}

// decodeString decodes a string from dynamic bytes
func decodeString(data []byte, offset int) (string, int, error) {
	bytes, nextOffset, err := decodeBytes(data, offset)
	if err != nil {
		return "", 0, err
	}
	return string(bytes), nextOffset, nil
} // Method information
func GetComplexFunctionMethod() MethodInfo {
	return MethodInfo{
		Name:      "complexFunction",
		Signature: "complexFunction(address[],uint256[],bytes,bool)",
		Selector:  HexData("0xabcd1234"),
	}
}
func GetGetMappingMethod() MethodInfo {
	return MethodInfo{
		Name:      "getMapping",
		Signature: "getMapping(bytes32)",
		Selector:  HexData("0x45678901"),
	}
}

// Event information
func GetComplexEventEvent() EventInfo {
	return EventInfo{
		Name:  "ComplexEvent",
		Topic: HashFromHex("0x962def339326e62b3c27608782d2aa3df88c18308ddbbb97838ae5ae5973c6e7"),
	}
}

// Error information
func GetComplexErrorError() ErrorInfo {
	return ErrorInfo{
		Name:      "ComplexError",
		Signature: "ComplexError(string,uint256)",
		Selector:  HexData("0xeaae9971"),
	}
}

// Method registry provides access to packable contract methods
type MethodRegistry struct{}

// Event registry provides access to packable contract events
type EventRegistry struct{}

// Error registry provides access to packable contract errors
type ErrorRegistry struct{}

// PackableMethod represents a method with packing capabilities
type PackableMethod struct {
	Name      string
	Signature string
	Selector  HexData
}

// PackableEvent represents an event with unpacking capabilities
type PackableEvent struct {
	Name  string
	Topic Hash
}

// EventDecoder represents an event with decode functionality
type EventDecoder struct {
	Name  string
	Topic Hash
}

// PackableError represents an error with unpacking capabilities
type PackableError struct {
	Name      string
	Signature string
	Selector  HexData
}

// MethodInfo represents method metadata
type MethodInfo struct {
	Name      string
	Signature string
	Selector  HexData
}

// EventInfo represents event metadata
type EventInfo struct {
	Name  string
	Topic Hash
}

// ErrorInfo represents error metadata
type ErrorInfo struct {
	Name      string
	Signature string
	Selector  HexData
}

// Pack encodes method arguments and returns the method selector + encoded arguments.
// Uses ABI head-tail encoding: static args are inlined in the head (32 bytes each);
// dynamic args (string, []byte) get a 32-byte offset pointer in the head, with
// their data appended in the tail section.
func (pm *PackableMethod) Pack(args ...any) (HexData, error) {
	// Start with the 4-byte method selector
	selectorBytes := pm.Selector.Bytes()
	if len(selectorBytes) == 0 {
		return "", fmt.Errorf("invalid method selector")
	}

	// If no arguments, return just the selector
	if len(args) == 0 {
		return pm.Selector, nil
	}

	type argEncoding struct {
		data      []byte
		isDynamic bool
	}

	encoded := make([]argEncoding, len(args))
	for i, arg := range args {
		data, dynamic, err := encodeArg(arg)
		if err != nil {
			return "", fmt.Errorf("encoding arg %d: %w", i, err)
		}
		encoded[i] = argEncoding{data: data, isDynamic: dynamic}
	}

	// Build ABI head-tail encoding:
	// Head: static args inlined (32 bytes); dynamic args get a 32-byte offset pointer.
	// Tail: dynamic args' encoded data appended in order.
	headSize := len(args) * 32
	tailOffset := headSize

	var head []byte
	var tail []byte
	for _, enc := range encoded {
		if enc.isDynamic {
			offsetBytes, err := encodeUint256(uint64(tailOffset))
			if err != nil {
				return "", fmt.Errorf("encoding offset pointer: %w", err)
			}
			head = append(head, offsetBytes...)
			tail = append(tail, enc.data...)
			tailOffset += len(enc.data)
		} else {
			head = append(head, enc.data...)
		}
	}

	payload := append(selectorBytes, append(head, tail...)...)
	return HexData("0x" + hex.EncodeToString(payload)), nil
}

// MustPack encodes method arguments and panics on error
func (pm *PackableMethod) MustPack(args ...any) HexData {
	result, err := pm.Pack(args...)
	if err != nil {
		panic(err)
	}
	return result
}

// ComplexFunctionMethod returns a packable method for complexFunction
func (mr MethodRegistry) ComplexFunctionMethod() *ComplexFunctionMethod {
	return &ComplexFunctionMethod{
		PackableMethod: PackableMethod{
			Name:      "complexFunction",
			Signature: "complexFunction(address[],uint256[],bytes,bool)",
			Selector:  HexData("0xabcd1234"),
		},
	}
}

// GetMappingMethod returns a packable method for getMapping
func (mr MethodRegistry) GetMappingMethod() *GetMappingMethod {
	return &GetMappingMethod{
		PackableMethod: PackableMethod{
			Name:      "getMapping",
			Signature: "getMapping(bytes32)",
			Selector:  HexData("0x45678901"),
		},
	}
}

// Methods returns the method registry
func Methods() MethodRegistry {
	return MethodRegistry{}
}

// ComplexFunctionMethod represents the complexFunction method with type-safe decode functionality
type ComplexFunctionMethod struct {
	PackableMethod
}

// GetMappingMethod represents the getMapping method with type-safe decode functionality
type GetMappingMethod struct {
	PackableMethod
}

// ComplexEventEventDecoder returns a decoder for ComplexEvent events
func (er EventRegistry) ComplexEventEventDecoder() *ComplexEventEventDecoder {
	return &ComplexEventEventDecoder{
		PackableEvent: PackableEvent{
			Name:  "ComplexEvent",
			Topic: HashFromHex("0x962def339326e62b3c27608782d2aa3df88c18308ddbbb97838ae5ae5973c6e7"),
		},
	}
}

// Events returns the event registry
func Events() EventRegistry {
	return EventRegistry{}
}

// ComplexEventEventDecoder represents the ComplexEvent event with type-safe decode functionality
type ComplexEventEventDecoder struct {
	PackableEvent
}

// ComplexErrorError returns a packable error for ComplexError
func (er ErrorRegistry) ComplexErrorError() *ComplexErrorErrorDecoder {
	return &ComplexErrorErrorDecoder{
		PackableError: PackableError{
			Name:      "ComplexError",
			Signature: "ComplexError(string,uint256)",
			Selector:  HexData("0xeaae9971"),
		},
	}
}

// Errors returns the error registry
func Errors() ErrorRegistry {
	return ErrorRegistry{}
}

// ComplexErrorErrorDecoder represents the ComplexError error with type-safe decode functionality
type ComplexErrorErrorDecoder struct {
	PackableError
}

// ComplexEventEvent represents the ComplexEvent event
type ComplexEventEvent struct {
	User      Address  `json:"user"`
	Data      []byte   `json:"data"`
	Timestamp *big.Int `json:"timestamp"`
}

// ComplexErrorError represents the ComplexError custom error
type ComplexErrorError struct {
	Reason string   `json:"reason"`
	Code   *big.Int `json:"code"`
}

// ComplexFunctionInput represents inputs for method complexFunction
type ComplexFunctionInput struct {
	Addresses []Address  `json:"addresses"`
	Amounts   []*big.Int `json:"amounts"`
	Data      []byte     `json:"data"`
	Flag      bool       `json:"flag"`
}

// ComplexFunctionOutput represents outputs for method complexFunction
type ComplexFunctionOutput struct {
	Success bool       `json:"success"`
	Results []*big.Int `json:"results"`
}

// ComplexFunctionResult represents the return values for complexFunction method
type ComplexFunctionResult struct {
	Success bool       `json:"success"`
	Results []*big.Int `json:"results"`
}

// Decode decodes return values for complexFunction method
func (m *ComplexFunctionMethod) Decode(data []byte) (ComplexFunctionResult, error) {
	return m.decodeImpl(data)
}

// MustDecode decodes return values for complexFunction method
func (m *ComplexFunctionMethod) MustDecode(data []byte) ComplexFunctionResult {
	result, err := m.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// decodeImpl contains the actual decode logic
func (m *ComplexFunctionMethod) decodeImpl(data []byte) (ComplexFunctionResult, error) {
	// Multiple return values - return as struct
	var result ComplexFunctionResult
	offset := 0
	if len(data) < offset+32 {
		return result, errors.New("insufficient data for return value 0")
	}
	{
		v, e := decodeBool(data[offset : offset+32])
		if e != nil {
			return result, fmt.Errorf("decoding return value 0: %w", e)
		}
		result.Success = v
	}
	offset += 32
	{
		s, e := decodeStaticSliceAt(data, offset, decodeUint256)
		if e != nil {
			return result, fmt.Errorf("decoding return value 1: %w", e)
		}
		result.Results = s
	}
	offset += 32
	return result, nil
}

// Decode decodes return values for getMapping method
func (m *GetMappingMethod) Decode(data []byte) (string, error) {
	return m.decodeImpl(data)
}

// MustDecode decodes return values for getMapping method
func (m *GetMappingMethod) MustDecode(data []byte) string {
	result, err := m.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// decodeImpl contains the actual decode logic
func (m *GetMappingMethod) decodeImpl(data []byte) (string, error) {
	var result string
	offset := 0
	{
		ptr, e := readOffset(data, offset)
		if e != nil {
			return result, fmt.Errorf("decoding return value: %w", e)
		}
		s, _, e2 := decodeString(data, ptr)
		if e2 != nil {
			return result, fmt.Errorf("decoding return value: %w", e2)
		}
		result = s
	}
	offset += 32
	return result, nil
}

// Decode decodes log data for ComplexEvent event
func (e *ComplexEventEventDecoder) Decode(data []byte) (ComplexEventEvent, error) {
	return e.decodeImpl(data)
}

// MustDecode decodes log data for ComplexEvent event
func (e *ComplexEventEventDecoder) MustDecode(data []byte) ComplexEventEvent {
	result, err := e.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// DecodeLog decodes a full log into ComplexEventEvent: non-indexed parameters are
// read from data, while indexed parameters are read from topics (topics[0] is the
// event signature, so indexed params start at topics[1]) in ABI order.
//
// Indexed dynamic types (string, bytes, arrays) are stored as the keccak hash of
// their value in the topic and cannot be recovered to their original value; such
// fields are left at their zero value.
func (e *ComplexEventEventDecoder) DecodeLog(topics [][32]byte, data []byte) (ComplexEventEvent, error) {
	// Non-indexed parameters live in the data section.
	result, err := e.decodeImpl(data)
	if err != nil {
		return result, err
	}
	// Indexed parameters live in the log topics, after the signature topic.
	topicIndex := 1
	if len(topics) <= topicIndex {
		return result, errors.New("missing topic for indexed parameter user")
	}
	{
		word := topics[topicIndex][:]
		v, e := decodeAddress(word)
		if e != nil {
			return result, fmt.Errorf("decoding indexed parameter user: %w", e)
		}
		result.User = v
	}
	topicIndex++
	if len(topics) <= topicIndex {
		return result, errors.New("missing topic for indexed parameter timestamp")
	}
	{
		word := topics[topicIndex][:]
		v, e := decodeUint256(word)
		if e != nil {
			return result, fmt.Errorf("decoding indexed parameter timestamp: %w", e)
		}
		result.Timestamp = v
	}
	topicIndex++
	return result, nil
}

// decodeImpl contains the actual decode logic
func (e *ComplexEventEventDecoder) decodeImpl(data []byte) (ComplexEventEvent, error) {
	// Decode event parameters (only non-indexed parameters are in data)
	var result ComplexEventEvent
	offset := 0
	{
		ptr, e := readOffset(data, offset)
		if e != nil {
			return result, fmt.Errorf("decoding event parameter data: %w", e)
		}
		b, _, e2 := decodeBytes(data, ptr)
		if e2 != nil {
			return result, fmt.Errorf("decoding event parameter data: %w", e2)
		}
		result.Data = b
	}
	offset += 32
	return result, nil
}

// Decode decodes error data for ComplexError error
func (e *ComplexErrorErrorDecoder) Decode(data []byte) (ComplexErrorError, error) {
	return e.decodeImpl(data)
}

// MustDecode decodes error data for ComplexError error
func (e *ComplexErrorErrorDecoder) MustDecode(data []byte) ComplexErrorError {
	result, err := e.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// decodeImpl contains the actual decode logic
func (e *ComplexErrorErrorDecoder) decodeImpl(data []byte) (ComplexErrorError, error) {
	// Skip the 4-byte selector
	if len(data) < 4 {
		return ComplexErrorError{}, errors.New("insufficient data for error selector")
	}
	var result ComplexErrorError
	errorData := data[4:]
	offset := 0
	{
		ptr, e := readOffset(errorData, offset)
		if e != nil {
			return result, fmt.Errorf("decoding error parameter reason: %w", e)
		}
		s, _, e2 := decodeString(errorData, ptr)
		if e2 != nil {
			return result, fmt.Errorf("decoding error parameter reason: %w", e2)
		}
		result.Reason = s
	}
	offset += 32
	if len(errorData) < offset+32 {
		return result, errors.New("insufficient data for error parameter code")
	}
	{
		v, e := decodeUint256(errorData[offset : offset+32])
		if e != nil {
			return result, fmt.Errorf("decoding error parameter code: %w", e)
		}
		result.Code = v
	}
	offset += 32
	return result, nil
}
