// Code generated by github.com/otherview/solgen. DO NOT EDIT.
// SPDX-License-Identifier: MIT
// Contract: ComplexContract (solc 0.8.20)

package complexcontract

import (
	"encoding/hex"
	"errors"
	"fmt"
	"math/big"
	"strings"
)

// Contract metadata
var _abiJSON = "[\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"function\",\n\t\t\t\t\t\"name\": \"complexFunction\",\n\t\t\t\t\t\"inputs\": [\n\t\t\t\t\t\t{\"name\": \"addresses\", \"type\": \"address[]\"},\n\t\t\t\t\t\t{\"name\": \"amounts\", \"type\": \"uint256[]\"},\n\t\t\t\t\t\t{\"name\": \"data\", \"type\": \"bytes\"},\n\t\t\t\t\t\t{\"name\": \"flag\", \"type\": \"bool\"}\n\t\t\t\t\t],\n\t\t\t\t\t\"outputs\": [\n\t\t\t\t\t\t{\"name\": \"success\", \"type\": \"bool\"},\n\t\t\t\t\t\t{\"name\": \"results\", \"type\": \"uint256[]\"}\n\t\t\t\t\t],\n\t\t\t\t\t\"stateMutability\": \"nonpayable\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"function\",\n\t\t\t\t\t\"name\": \"getMapping\",\n\t\t\t\t\t\"inputs\": [{\"name\": \"key\", \"type\": \"bytes32\"}],\n\t\t\t\t\t\"outputs\": [{\"name\": \"value\", \"type\": \"string\"}],\n\t\t\t\t\t\"stateMutability\": \"view\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"event\",\n\t\t\t\t\t\"name\": \"ComplexEvent\", \n\t\t\t\t\t\"inputs\": [\n\t\t\t\t\t\t{\"name\": \"user\", \"type\": \"address\", \"indexed\": true},\n\t\t\t\t\t\t{\"name\": \"data\", \"type\": \"bytes\", \"indexed\": false},\n\t\t\t\t\t\t{\"name\": \"timestamp\", \"type\": \"uint256\", \"indexed\": true}\n\t\t\t\t\t]\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"type\": \"error\",\n\t\t\t\t\t\"name\": \"ComplexError\",\n\t\t\t\t\t\"inputs\": [\n\t\t\t\t\t\t{\"name\": \"reason\", \"type\": \"string\"},\n\t\t\t\t\t\t{\"name\": \"code\", \"type\": \"uint256\"}\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t]"

// ABI returns the contract ABI as a JSON string
func ABI() string {
	return _abiJSON
}

// Bytecode contains the contract creation bytecode
var Bytecode = HexData("0x608060405234801561001057600080fd5b50610abc806100206000396000f3fe")

// DeployedBytecode contains the contract runtime bytecode
var DeployedBytecode = HexData("0x6080604052348015600f57600080fd5b50600436106100365760003560e01c8063abcd123414603a5780634567890114603f565b5b600080fd5b005b005b600080fd5b6000819050919050565b60558160048565b8114605f57600080fd5b50565b6000813590506070816050565b92915050565b6000602082840312156088576087600b565b5b600060948482850160635b915050929150505056fea264697066735822")

// Address represents a 20-byte Ethereum address
type Address [20]byte

// String returns the hex string representation of the address
func (a Address) String() string {
	return "0x" + hex.EncodeToString(a[:])
}

// Hash represents a 32-byte hash
type Hash [32]byte

// String returns the hex string representation of the hash
func (h Hash) String() string {
	return "0x" + hex.EncodeToString(h[:])
}

// Bytes returns the hash as a byte slice
func (h Hash) Bytes() []byte {
	return h[:]
}

// AddressFromHex creates an Address from a hex string
func AddressFromHex(s string) Address {
	var addr Address
	if strings.HasPrefix(s, "0x") {
		s = s[2:]
	}
	if len(s) != 40 {
		panic("invalid address hex string length")
	}
	decoded, err := hex.DecodeString(s)
	if err != nil {
		panic("invalid address hex string: " + err.Error())
	}
	copy(addr[:], decoded)
	return addr
}

// HashFromHex creates a Hash from a hex string
func HashFromHex(s string) Hash {
	var hash Hash
	if strings.HasPrefix(s, "0x") {
		s = s[2:]
	}
	if len(s) != 64 {
		panic("invalid hash hex string length")
	}
	decoded, err := hex.DecodeString(s)
	if err != nil {
		panic("invalid hash hex string: " + err.Error())
	}
	copy(hash[:], decoded)
	return hash
}

// HexData provides convenient access to hex-encoded byte data
type HexData string

// Hex returns the hex string representation
func (h HexData) Hex() string {
	return string(h)
}

// Bytes returns the decoded bytes from the hex string
func (h HexData) Bytes() []byte {
	hexStr := string(h)
	if hexStr == "" {
		return nil
	}
	if strings.HasPrefix(hexStr, "0x") {
		hexStr = hexStr[2:]
	}
	decoded, err := hex.DecodeString(hexStr)
	if err != nil {
		panic("invalid hex data: " + err.Error())
	}
	return decoded
}

// ABI Encoding Implementation

// encodeUint256 encodes a uint256 value to 32 bytes (big-endian)
func encodeUint256(val interface{}) ([]byte, error) {
	result := make([]byte, 32)
	switch v := val.(type) {
	case *big.Int:
		if v.Sign() < 0 {
			return nil, errors.New("negative values not supported for uint256")
		}
		if v.BitLen() > 256 {
			return nil, errors.New("value too large for uint256")
		}
		v.FillBytes(result)
		return result, nil
	case uint64:
		big.NewInt(0).SetUint64(v).FillBytes(result)
		return result, nil
	case int64:
		if v < 0 {
			return nil, errors.New("negative values not supported for uint256")
		}
		big.NewInt(v).FillBytes(result)
		return result, nil
	case int:
		if v < 0 {
			return nil, errors.New("negative values not supported for uint256")
		}
		big.NewInt(int64(v)).FillBytes(result)
		return result, nil
	default:
		return nil, fmt.Errorf("unsupported type for uint256: %T", v)
	}
}

// encodeInt256 encodes a signed 256-bit integer to 32 bytes using two's complement
func encodeInt256(val interface{}) ([]byte, error) {
	result := make([]byte, 32)
	switch v := val.(type) {
	case *big.Int:
		// Check if value fits in 256 bits (considering sign)
		if v.BitLen() >= 256 {
			return nil, errors.New("value too large for int256")
		}

		if v.Sign() >= 0 {
			// Positive number - same as uint256
			v.FillBytes(result)
		} else {
			// Negative number - use two's complement
			// Create a 256-bit mask (all 1s)
			mask := new(big.Int).Lsh(big.NewInt(1), 256)
			mask.Sub(mask, big.NewInt(1))

			// Get absolute value, subtract 1, XOR with mask
			abs := new(big.Int).Neg(v)
			abs.Sub(abs, big.NewInt(1))
			abs.Xor(abs, mask)
			abs.FillBytes(result)
		}
		return result, nil
	case int64:
		return encodeInt256(big.NewInt(v))
	case int:
		return encodeInt256(big.NewInt(int64(v)))
	default:
		return nil, fmt.Errorf("unsupported type for int256: %T", v)
	}
}

// encodeAddress encodes an address to 32 bytes (zero-padded)
func encodeAddress(addr Address) ([]byte, error) {
	result := make([]byte, 32)
	copy(result[12:32], addr[:])
	return result, nil
}

// encodeBool encodes a boolean to 32 bytes
func encodeBool(val bool) ([]byte, error) {
	result := make([]byte, 32)
	if val {
		result[31] = 1
	}
	return result, nil
}

// encodeBytes encodes dynamic bytes
func encodeBytes(data []byte) ([]byte, error) {
	// Length (32 bytes) + data (padded to multiple of 32 bytes)
	length := len(data)
	lengthBytes, err := encodeUint256(uint64(length))
	if err != nil {
		return nil, err
	}

	// Pad data to multiple of 32 bytes
	paddedLength := ((length + 31) / 32) * 32
	paddedData := make([]byte, paddedLength)
	copy(paddedData, data)

	return append(lengthBytes, paddedData...), nil
}

// encodeString encodes a string as dynamic bytes
func encodeString(str string) ([]byte, error) {
	return encodeBytes([]byte(str))
}

// ABI Decoding Implementation

// decodeUint256 decodes a uint256 from 32 bytes to *big.Int
func decodeUint256(data []byte) (*big.Int, error) {
	if len(data) < 32 {
		return nil, errors.New("insufficient data for uint256")
	}
	return new(big.Int).SetBytes(data[:32]), nil
}

// decodeInt256 decodes a signed 256-bit integer from 32 bytes
func decodeInt256(data []byte) (*big.Int, error) {
	if len(data) < 32 {
		return nil, errors.New("insufficient data for int256")
	}

	result := new(big.Int).SetBytes(data[:32])

	// Check if negative (MSB is set)
	if data[0]&0x80 != 0 {
		// Convert from two's complement
		// Create mask with all bits set for 256-bit number
		mask := new(big.Int).Lsh(big.NewInt(1), 256)
		mask.Sub(mask, big.NewInt(1))

		// XOR with mask and add 1 to get absolute value
		result.Xor(result, mask)
		result.Add(result, big.NewInt(1))
		result.Neg(result)
	}

	return result, nil
}

// decodeAddress decodes an address from 32 bytes
func decodeAddress(data []byte) (Address, error) {
	if len(data) < 32 {
		return Address{}, errors.New("insufficient data for address")
	}
	var addr Address
	copy(addr[:], data[12:32])
	return addr, nil
}

// decodeBool decodes a boolean from 32 bytes
func decodeBool(data []byte) (bool, error) {
	if len(data) < 32 {
		return false, errors.New("insufficient data for bool")
	}
	return data[31] != 0, nil
}

// decodeBytes decodes dynamic bytes
func decodeBytes(data []byte, offset int) ([]byte, int, error) {
	if len(data) < offset+32 {
		return nil, 0, errors.New("insufficient data for bytes length")
	}
	lengthBig, err := decodeUint256(data[offset : offset+32])
	if err != nil {
		return nil, 0, fmt.Errorf("decoding bytes length: %w", err)
	}
	if !lengthBig.IsUint64() {
		return nil, 0, errors.New("bytes length too large")
	}
	length := int(lengthBig.Uint64())
	if len(data) < offset+32+length {
		return nil, 0, errors.New("insufficient data for bytes content")
	}
	result := make([]byte, length)
	copy(result, data[offset+32:offset+32+length])
	// Calculate next offset (padded to 32 bytes)
	paddedLength := ((length + 31) / 32) * 32
	return result, offset + 32 + paddedLength, nil
}

// decodeFixedBytes decodes fixed-size bytes (e.g., bytes32)
func decodeFixedBytes(data []byte, size int) ([]byte, error) {
	if len(data) < 32 {
		return nil, errors.New("insufficient data for fixed bytes")
	}
	if size > 32 {
		return nil, errors.New("fixed bytes size too large")
	}
	result := make([]byte, size)
	copy(result, data[:size])
	return result, nil
}

// decode various fixed-size byte arrays
func decodeBytes1(data []byte) ([1]byte, error) {
	bytes, err := decodeFixedBytes(data, 1)
	if err != nil {
		return [1]byte{}, err
	}
	var result [1]byte
	copy(result[:], bytes)
	return result, nil
}

func decodeBytes32(data []byte) ([32]byte, error) {
	bytes, err := decodeFixedBytes(data, 32)
	if err != nil {
		return [32]byte{}, err
	}
	var result [32]byte
	copy(result[:], bytes)
	return result, nil
}

// decodeArray decodes dynamic arrays
func decodeArray(data []byte, offset int, elemDecoder func([]byte) (interface{}, error)) ([]interface{}, int, error) {
	if len(data) < offset+32 {
		return nil, 0, errors.New("insufficient data for array length")
	}

	lengthBig, err := decodeUint256(data[offset : offset+32])
	if err != nil {
		return nil, 0, fmt.Errorf("decoding array length: %w", err)
	}
	if !lengthBig.IsUint64() {
		return nil, 0, errors.New("array length too large")
	}
	length := int(lengthBig.Uint64())

	currentOffset := offset + 32
	result := make([]interface{}, length)

	for i := 0; i < length; i++ {
		if len(data) < currentOffset+32 {
			return nil, 0, fmt.Errorf("insufficient data for array element %d", i)
		}
		elem, err := elemDecoder(data[currentOffset : currentOffset+32])
		if err != nil {
			return nil, 0, fmt.Errorf("decoding array element %d: %w", i, err)
		}
		result[i] = elem
		currentOffset += 32
	}

	return result, currentOffset, nil
}

// Array element decoders (internal use)
func decodeUint256ArrayElement(data []byte) (interface{}, error) {
	return decodeUint256(data)
}

func decodeInt256ArrayElement(data []byte) (interface{}, error) {
	return decodeInt256(data)
}

func decodeAddressArrayElement(data []byte) (interface{}, error) {
	return decodeAddress(data)
}

func decodeBoolArrayElement(data []byte) (interface{}, error) {
	return decodeBool(data)
}

// decodeUint8 decodes a uint8 from 32 bytes
func decodeUint8(data []byte) (uint8, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint8")
	}
	// Verify upper bytes are zero
	for i := 0; i < 31; i++ {
		if data[i] != 0 {
			return 0, errors.New("invalid uint8 encoding")
		}
	}
	return data[31], nil
}

// decodeUint16 decodes a uint16 from 32 bytes
func decodeUint16(data []byte) (uint16, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint16")
	}
	// Verify upper bytes are zero
	for i := 0; i < 30; i++ {
		if data[i] != 0 {
			return 0, errors.New("invalid uint16 encoding")
		}
	}
	return uint16(data[30])<<8 | uint16(data[31]), nil
}

// decodeUint32 decodes a uint32 from 32 bytes
func decodeUint32(data []byte) (uint32, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint32")
	}
	// Verify upper bytes are zero
	for i := 0; i < 28; i++ {
		if data[i] != 0 {
			return 0, errors.New("invalid uint32 encoding")
		}
	}
	var result uint32
	for i := 28; i < 32; i++ {
		result = (result << 8) | uint32(data[i])
	}
	return result, nil
}

// decodeUint64 decodes a uint64 from 32 bytes
func decodeUint64(data []byte) (uint64, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for uint64")
	}
	// Check if value exceeds uint64 range
	for i := 0; i < 24; i++ {
		if data[i] != 0 {
			return 0, errors.New("value exceeds uint64 range")
		}
	}
	var result uint64
	for i := 24; i < 32; i++ {
		result = (result << 8) | uint64(data[i])
	}
	return result, nil
}

// decodeInt64 decodes a int64 from 32 bytes
func decodeInt64(data []byte) (int64, error) {
	if len(data) < 32 {
		return 0, errors.New("insufficient data for int64")
	}

	// Check if this is a negative number (MSB set)
	isNegative := data[0]&0x80 != 0

	// Verify upper bytes are consistent (all 0s or all 1s for sign extension)
	expectedByte := byte(0)
	if isNegative {
		expectedByte = 0xFF
	}

	for i := 0; i < 24; i++ {
		if data[i] != expectedByte {
			return 0, errors.New("value exceeds int64 range")
		}
	}

	var result int64
	for i := 24; i < 32; i++ {
		result = (result << 8) | int64(data[i])
	}

	// Sign extend if necessary
	if isNegative {
		result |= ^((1 << 32) - 1) // Set upper 32 bits
	}

	return result, nil
}

// decodeHash decodes a 32-byte hash
func decodeHash(data []byte) (Hash, error) {
	if len(data) < 32 {
		return Hash{}, errors.New("insufficient data for hash")
	}
	var hash Hash
	copy(hash[:], data[:32])
	return hash, nil
}

// decodeString decodes a string from dynamic bytes
func decodeString(data []byte, offset int) (string, int, error) {
	bytes, nextOffset, err := decodeBytes(data, offset)
	if err != nil {
		return "", 0, err
	}
	return string(bytes), nextOffset, nil
}

// Method information
func GetComplexFunctionMethod() MethodInfo {
	return MethodInfo{
		Name:      "complexFunction",
		Signature: "complexFunction(address[],uint256[],bytes,bool)",
		Selector:  HexData("0xabcd1234"),
	}
}
func GetGetMappingMethod() MethodInfo {
	return MethodInfo{
		Name:      "getMapping",
		Signature: "getMapping(bytes32)",
		Selector:  HexData("0x45678901"),
	}
}

// Event information
func GetComplexEventEvent() EventInfo {
	return EventInfo{
		Name:  "ComplexEvent",
		Topic: HashFromHex("0x962def339326e62b3c27608782d2aa3df88c18308ddbbb97838ae5ae5973c6e7"),
	}
}

// Error information
func GetComplexErrorError() ErrorInfo {
	return ErrorInfo{
		Name:      "ComplexError",
		Signature: "ComplexError(string,uint256)",
		Selector:  HexData("0xeaae9971"),
	}
}

// Method registry provides access to packable contract methods
type MethodRegistry struct{}

// Event registry provides access to packable contract events
type EventRegistry struct{}

// Error registry provides access to packable contract errors
type ErrorRegistry struct{}

// PackableMethod represents a method with packing capabilities
type PackableMethod struct {
	Name      string
	Signature string
	Selector  HexData
}

// PackableEvent represents an event with unpacking capabilities
type PackableEvent struct {
	Name  string
	Topic Hash
}

// EventDecoder represents an event with decode functionality
type EventDecoder struct {
	Name  string
	Topic Hash
}

// PackableError represents an error with unpacking capabilities
type PackableError struct {
	Name      string
	Signature string
	Selector  HexData
}

// MethodInfo represents method metadata
type MethodInfo struct {
	Name      string
	Signature string
	Selector  HexData
}

// EventInfo represents event metadata
type EventInfo struct {
	Name  string
	Topic Hash
}

// ErrorInfo represents error metadata
type ErrorInfo struct {
	Name      string
	Signature string
	Selector  HexData
}

// Pack encodes method arguments and returns the method selector + encoded arguments
func (pm *PackableMethod) Pack(args ...any) (HexData, error) {
	// Start with the 4-byte method selector
	selectorBytes := pm.Selector.Bytes()
	if len(selectorBytes) == 0 {
		return "", fmt.Errorf("invalid method selector")
	}

	// If no arguments, return just the selector
	if len(args) == 0 {
		return pm.Selector, nil
	}

	// Encode arguments using our ABI implementation
	var encodedArgs []byte
	for _, arg := range args {
		switch v := arg.(type) {
		case *big.Int:
			data, err := encodeUint256(v)
			if err != nil {
				return "", fmt.Errorf("encoding big.Int: %w", err)
			}
			encodedArgs = append(encodedArgs, data...)
		case Address:
			data, err := encodeAddress(v)
			if err != nil {
				return "", fmt.Errorf("encoding address: %w", err)
			}
			encodedArgs = append(encodedArgs, data...)
		case bool:
			data, err := encodeBool(v)
			if err != nil {
				return "", fmt.Errorf("encoding bool: %w", err)
			}
			encodedArgs = append(encodedArgs, data...)
		case string:
			data, err := encodeString(v)
			if err != nil {
				return "", fmt.Errorf("encoding string: %w", err)
			}
			encodedArgs = append(encodedArgs, data...)
		case []byte:
			data, err := encodeBytes(v)
			if err != nil {
				return "", fmt.Errorf("encoding bytes: %w", err)
			}
			encodedArgs = append(encodedArgs, data...)
		default:
			return "", fmt.Errorf("unsupported argument type: %T", arg)
		}
	}

	// Combine selector and encoded arguments
	result := hex.EncodeToString(append(selectorBytes, encodedArgs...))
	return HexData("0x" + result), nil
}

// MustPack encodes method arguments and panics on error
func (pm *PackableMethod) MustPack(args ...any) HexData {
	result, err := pm.Pack(args...)
	if err != nil {
		panic(err)
	}
	return result
}

// ComplexFunctionMethod returns a packable method for complexFunction
func (mr MethodRegistry) ComplexFunctionMethod() *ComplexFunctionMethod {
	return &ComplexFunctionMethod{
		PackableMethod: PackableMethod{
			Name:      "complexFunction",
			Signature: "complexFunction(address[],uint256[],bytes,bool)",
			Selector:  HexData("0xabcd1234"),
		},
	}
}

// GetMappingMethod returns a packable method for getMapping
func (mr MethodRegistry) GetMappingMethod() *GetMappingMethod {
	return &GetMappingMethod{
		PackableMethod: PackableMethod{
			Name:      "getMapping",
			Signature: "getMapping(bytes32)",
			Selector:  HexData("0x45678901"),
		},
	}
}

// Methods returns the method registry
func Methods() MethodRegistry {
	return MethodRegistry{}
}

// ComplexFunctionMethod represents the complexFunction method with type-safe decode functionality
type ComplexFunctionMethod struct {
	PackableMethod
}

// GetMappingMethod represents the getMapping method with type-safe decode functionality
type GetMappingMethod struct {
	PackableMethod
}

// ComplexEventEventDecoder returns a decoder for ComplexEvent events
func (er EventRegistry) ComplexEventEventDecoder() *ComplexEventEventDecoder {
	return &ComplexEventEventDecoder{
		PackableEvent: PackableEvent{
			Name:  "ComplexEvent",
			Topic: HashFromHex("0x962def339326e62b3c27608782d2aa3df88c18308ddbbb97838ae5ae5973c6e7"),
		},
	}
}

// Events returns the event registry
func Events() EventRegistry {
	return EventRegistry{}
}

// ComplexEventEventDecoder represents the ComplexEvent event with type-safe decode functionality
type ComplexEventEventDecoder struct {
	PackableEvent
}

// ComplexErrorError returns a packable error for ComplexError
func (er ErrorRegistry) ComplexErrorError() *ComplexErrorErrorDecoder {
	return &ComplexErrorErrorDecoder{
		PackableError: PackableError{
			Name:      "ComplexError",
			Signature: "ComplexError(string,uint256)",
			Selector:  HexData("0xeaae9971"),
		},
	}
}

// Errors returns the error registry
func Errors() ErrorRegistry {
	return ErrorRegistry{}
}

// ComplexErrorErrorDecoder represents the ComplexError error with type-safe decode functionality
type ComplexErrorErrorDecoder struct {
	PackableError
}

// ComplexEventEvent represents the ComplexEvent event
type ComplexEventEvent struct {
	User      Address  `json:"user"`
	Data      []byte   `json:"data"`
	Timestamp *big.Int `json:"timestamp"`
}

// ComplexErrorError represents the ComplexError custom error
type ComplexErrorError struct {
	Reason string   `json:"reason"`
	Code   *big.Int `json:"code"`
}

// ComplexFunctionInput represents inputs for method complexFunction
type ComplexFunctionInput struct {
	Addresses []Address  `json:"addresses"`
	Amounts   []*big.Int `json:"amounts"`
	Data      []byte     `json:"data"`
	Flag      bool       `json:"flag"`
}

// ComplexFunctionOutput represents outputs for method complexFunction
type ComplexFunctionOutput struct {
	Success bool       `json:"success"`
	Results []*big.Int `json:"results"`
}

// ComplexFunctionResult represents the return values for complexFunction method
type ComplexFunctionResult struct {
	Success bool       `json:"success"`
	Results []*big.Int `json:"results"`
}

// Decode decodes return values for complexFunction method
func (m *ComplexFunctionMethod) Decode(data []byte) (ComplexFunctionResult, error) {
	return m.decodeImpl(data)
}

// MustDecode decodes return values for complexFunction method
func (m *ComplexFunctionMethod) MustDecode(data []byte) ComplexFunctionResult {
	result, err := m.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// decodeImpl contains the actual decode logic
func (m *ComplexFunctionMethod) decodeImpl(data []byte) (ComplexFunctionResult, error) {
	// Multiple return values - return as struct
	var result ComplexFunctionResult
	var valBool bool
	var err error
	offset := 0
	if len(data) < offset+32 {
		return result, errors.New("insufficient data for return value 0")
	}
	valBool, err = decodeBool(data[offset : offset+32])
	if err != nil {
		return result, fmt.Errorf("decoding return value 0: %w", err)
	}
	result.Success = valBool
	offset += 32
	// Handle []*big.Int array
	var elems []interface{}
	var nextOffset int
	elems, nextOffset, err = decodeArray(data, offset, decodeUint256ArrayElement)
	if err != nil {
		return result, fmt.Errorf("decoding return value 1: %w", err)
	}
	bigIntArray := make([]*big.Int, len(elems))
	for j, elem := range elems {
		bigIntArray[j] = elem.(*big.Int)
	}
	result.Results = bigIntArray
	offset = nextOffset
	return result, nil
}

// Decode decodes return values for getMapping method
func (m *GetMappingMethod) Decode(data []byte) (string, error) {
	return m.decodeImpl(data)
}

// MustDecode decodes return values for getMapping method
func (m *GetMappingMethod) MustDecode(data []byte) string {
	result, err := m.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// decodeImpl contains the actual decode logic
func (m *GetMappingMethod) decodeImpl(data []byte) (string, error) {
	// Single return value - use unified decoding approach
	offset := 0
	result, _, err := decodeString(data, offset)
	return result, err
}

// Decode decodes log data for ComplexEvent event
func (e *ComplexEventEventDecoder) Decode(data []byte) (ComplexEventEvent, error) {
	return e.decodeImpl(data)
}

// MustDecode decodes log data for ComplexEvent event
func (e *ComplexEventEventDecoder) MustDecode(data []byte) ComplexEventEvent {
	result, err := e.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// decodeImpl contains the actual decode logic
func (e *ComplexEventEventDecoder) decodeImpl(data []byte) (ComplexEventEvent, error) {
	// Decode event parameters (only non-indexed parameters are in data)
	var result ComplexEventEvent
	var valBytes []byte
	var err error
	offset := 0
	var nextOffset int
	valBytes, nextOffset, err = decodeBytes(data, offset)
	if err != nil {
		return result, fmt.Errorf("decoding event parameter data: %w", err)
	}
	result.Data = valBytes
	offset = nextOffset
	return result, nil
}

// Decode decodes error data for ComplexError error
func (e *ComplexErrorErrorDecoder) Decode(data []byte) (ComplexErrorError, error) {
	return e.decodeImpl(data)
}

// MustDecode decodes error data for ComplexError error
func (e *ComplexErrorErrorDecoder) MustDecode(data []byte) ComplexErrorError {
	result, err := e.decodeImpl(data)
	if err != nil {
		panic(err)
	}
	return result
}

// decodeImpl contains the actual decode logic
func (e *ComplexErrorErrorDecoder) decodeImpl(data []byte) (ComplexErrorError, error) {
	// Skip the 4-byte selector
	if len(data) < 4 {
		return ComplexErrorError{}, errors.New("insufficient data for error selector")
	}
	errorData := data[4:]
	// Decode error parameters
	var result ComplexErrorError
	var err error
	offset := 0
	val0, nextOffset, err := decodeString(errorData, offset)
	if err != nil {
		return result, fmt.Errorf("decoding error parameter reason: %w", err)
	}
	result.Reason = val0
	offset = nextOffset
	if len(errorData) < offset+32 {
		return result, errors.New("insufficient data for error parameter code")
	}
	val1, err := decodeUint256(errorData[offset : offset+32])
	if err != nil {
		return result, fmt.Errorf("decoding error parameter code: %w", err)
	}
	result.Code = val1
	offset += 32
	return result, nil
}
